// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.29.2
// source: scheduler/v1/scheduler.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSchedulerCancelExecution = "/scheduler.v1.Scheduler/CancelExecution"
const OperationSchedulerCreateTask = "/scheduler.v1.Scheduler/CreateTask"
const OperationSchedulerDeleteTask = "/scheduler.v1.Scheduler/DeleteTask"
const OperationSchedulerExecuteTask = "/scheduler.v1.Scheduler/ExecuteTask"
const OperationSchedulerGetExecution = "/scheduler.v1.Scheduler/GetExecution"
const OperationSchedulerGetTask = "/scheduler.v1.Scheduler/GetTask"
const OperationSchedulerGetTaskExecutions = "/scheduler.v1.Scheduler/GetTaskExecutions"
const OperationSchedulerListTasks = "/scheduler.v1.Scheduler/ListTasks"
const OperationSchedulerPauseTask = "/scheduler.v1.Scheduler/PauseTask"
const OperationSchedulerResumeTask = "/scheduler.v1.Scheduler/ResumeTask"
const OperationSchedulerUpdateTask = "/scheduler.v1.Scheduler/UpdateTask"

type SchedulerHTTPServer interface {
	// CancelExecution 取消执行中的任务
	CancelExecution(context.Context, *CancelExecutionRequest) (*ExecutionReply, error)
	// CreateTask 创建任务
	CreateTask(context.Context, *CreateTaskRequest) (*TaskReply, error)
	// DeleteTask 删除任务
	DeleteTask(context.Context, *DeleteTaskRequest) (*emptypb.Empty, error)
	// ExecuteTask 立即执行任务
	ExecuteTask(context.Context, *ExecuteTaskRequest) (*TaskExecutionReply, error)
	// GetExecution 获取单次执行详情
	GetExecution(context.Context, *GetExecutionRequest) (*ExecutionReply, error)
	// GetTask 获取任务详情
	GetTask(context.Context, *GetTaskRequest) (*TaskReply, error)
	// GetTaskExecutions 获取任务执行历史
	GetTaskExecutions(context.Context, *GetTaskExecutionsRequest) (*ListExecutionsReply, error)
	// ListTasks 任务列表查询
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksReply, error)
	// PauseTask 暂停任务
	PauseTask(context.Context, *PauseTaskRequest) (*TaskReply, error)
	// ResumeTask 恢复任务
	ResumeTask(context.Context, *ResumeTaskRequest) (*TaskReply, error)
	// UpdateTask 更新任务
	UpdateTask(context.Context, *UpdateTaskRequest) (*TaskReply, error)
}

func RegisterSchedulerHTTPServer(s *http.Server, srv SchedulerHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/tasks", _Scheduler_CreateTask0_HTTP_Handler(srv))
	r.GET("/api/v1/tasks/{id}", _Scheduler_GetTask0_HTTP_Handler(srv))
	r.PUT("/api/v1/tasks/{id}", _Scheduler_UpdateTask0_HTTP_Handler(srv))
	r.DELETE("/api/v1/tasks/{id}", _Scheduler_DeleteTask0_HTTP_Handler(srv))
	r.GET("/api/v1/tasks", _Scheduler_ListTasks0_HTTP_Handler(srv))
	r.POST("/api/v1/tasks/{id}/execute", _Scheduler_ExecuteTask0_HTTP_Handler(srv))
	r.POST("/api/v1/tasks/{id}/pause", _Scheduler_PauseTask0_HTTP_Handler(srv))
	r.POST("/api/v1/tasks/{id}/resume", _Scheduler_ResumeTask0_HTTP_Handler(srv))
	r.GET("/api/v1/tasks/{task_id}/executions", _Scheduler_GetTaskExecutions0_HTTP_Handler(srv))
	r.GET("/api/v1/executions/{id}", _Scheduler_GetExecution0_HTTP_Handler(srv))
	r.POST("/api/v1/executions/{id}/cancel", _Scheduler_CancelExecution0_HTTP_Handler(srv))
}

func _Scheduler_CreateTask0_HTTP_Handler(srv SchedulerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateTaskRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSchedulerCreateTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateTask(ctx, req.(*CreateTaskRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TaskReply)
		return ctx.Result(200, reply)
	}
}

func _Scheduler_GetTask0_HTTP_Handler(srv SchedulerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTaskRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSchedulerGetTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTask(ctx, req.(*GetTaskRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TaskReply)
		return ctx.Result(200, reply)
	}
}

func _Scheduler_UpdateTask0_HTTP_Handler(srv SchedulerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateTaskRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSchedulerUpdateTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateTask(ctx, req.(*UpdateTaskRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TaskReply)
		return ctx.Result(200, reply)
	}
}

func _Scheduler_DeleteTask0_HTTP_Handler(srv SchedulerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteTaskRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSchedulerDeleteTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteTask(ctx, req.(*DeleteTaskRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _Scheduler_ListTasks0_HTTP_Handler(srv SchedulerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListTasksRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSchedulerListTasks)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListTasks(ctx, req.(*ListTasksRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListTasksReply)
		return ctx.Result(200, reply)
	}
}

func _Scheduler_ExecuteTask0_HTTP_Handler(srv SchedulerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ExecuteTaskRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSchedulerExecuteTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ExecuteTask(ctx, req.(*ExecuteTaskRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TaskExecutionReply)
		return ctx.Result(200, reply)
	}
}

func _Scheduler_PauseTask0_HTTP_Handler(srv SchedulerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PauseTaskRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSchedulerPauseTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PauseTask(ctx, req.(*PauseTaskRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TaskReply)
		return ctx.Result(200, reply)
	}
}

func _Scheduler_ResumeTask0_HTTP_Handler(srv SchedulerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ResumeTaskRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSchedulerResumeTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ResumeTask(ctx, req.(*ResumeTaskRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TaskReply)
		return ctx.Result(200, reply)
	}
}

func _Scheduler_GetTaskExecutions0_HTTP_Handler(srv SchedulerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTaskExecutionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSchedulerGetTaskExecutions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTaskExecutions(ctx, req.(*GetTaskExecutionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListExecutionsReply)
		return ctx.Result(200, reply)
	}
}

func _Scheduler_GetExecution0_HTTP_Handler(srv SchedulerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetExecutionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSchedulerGetExecution)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetExecution(ctx, req.(*GetExecutionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ExecutionReply)
		return ctx.Result(200, reply)
	}
}

func _Scheduler_CancelExecution0_HTTP_Handler(srv SchedulerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CancelExecutionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSchedulerCancelExecution)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CancelExecution(ctx, req.(*CancelExecutionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ExecutionReply)
		return ctx.Result(200, reply)
	}
}

type SchedulerHTTPClient interface {
	// CancelExecution 取消执行中的任务
	CancelExecution(ctx context.Context, req *CancelExecutionRequest, opts ...http.CallOption) (rsp *ExecutionReply, err error)
	// CreateTask 创建任务
	CreateTask(ctx context.Context, req *CreateTaskRequest, opts ...http.CallOption) (rsp *TaskReply, err error)
	// DeleteTask 删除任务
	DeleteTask(ctx context.Context, req *DeleteTaskRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// ExecuteTask 立即执行任务
	ExecuteTask(ctx context.Context, req *ExecuteTaskRequest, opts ...http.CallOption) (rsp *TaskExecutionReply, err error)
	// GetExecution 获取单次执行详情
	GetExecution(ctx context.Context, req *GetExecutionRequest, opts ...http.CallOption) (rsp *ExecutionReply, err error)
	// GetTask 获取任务详情
	GetTask(ctx context.Context, req *GetTaskRequest, opts ...http.CallOption) (rsp *TaskReply, err error)
	// GetTaskExecutions 获取任务执行历史
	GetTaskExecutions(ctx context.Context, req *GetTaskExecutionsRequest, opts ...http.CallOption) (rsp *ListExecutionsReply, err error)
	// ListTasks 任务列表查询
	ListTasks(ctx context.Context, req *ListTasksRequest, opts ...http.CallOption) (rsp *ListTasksReply, err error)
	// PauseTask 暂停任务
	PauseTask(ctx context.Context, req *PauseTaskRequest, opts ...http.CallOption) (rsp *TaskReply, err error)
	// ResumeTask 恢复任务
	ResumeTask(ctx context.Context, req *ResumeTaskRequest, opts ...http.CallOption) (rsp *TaskReply, err error)
	// UpdateTask 更新任务
	UpdateTask(ctx context.Context, req *UpdateTaskRequest, opts ...http.CallOption) (rsp *TaskReply, err error)
}

type SchedulerHTTPClientImpl struct {
	cc *http.Client
}

func NewSchedulerHTTPClient(client *http.Client) SchedulerHTTPClient {
	return &SchedulerHTTPClientImpl{client}
}

// CancelExecution 取消执行中的任务
func (c *SchedulerHTTPClientImpl) CancelExecution(ctx context.Context, in *CancelExecutionRequest, opts ...http.CallOption) (*ExecutionReply, error) {
	var out ExecutionReply
	pattern := "/api/v1/executions/{id}/cancel"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSchedulerCancelExecution))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateTask 创建任务
func (c *SchedulerHTTPClientImpl) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...http.CallOption) (*TaskReply, error) {
	var out TaskReply
	pattern := "/api/v1/tasks"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSchedulerCreateTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteTask 删除任务
func (c *SchedulerHTTPClientImpl) DeleteTask(ctx context.Context, in *DeleteTaskRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/v1/tasks/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSchedulerDeleteTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ExecuteTask 立即执行任务
func (c *SchedulerHTTPClientImpl) ExecuteTask(ctx context.Context, in *ExecuteTaskRequest, opts ...http.CallOption) (*TaskExecutionReply, error) {
	var out TaskExecutionReply
	pattern := "/api/v1/tasks/{id}/execute"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSchedulerExecuteTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetExecution 获取单次执行详情
func (c *SchedulerHTTPClientImpl) GetExecution(ctx context.Context, in *GetExecutionRequest, opts ...http.CallOption) (*ExecutionReply, error) {
	var out ExecutionReply
	pattern := "/api/v1/executions/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSchedulerGetExecution))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetTask 获取任务详情
func (c *SchedulerHTTPClientImpl) GetTask(ctx context.Context, in *GetTaskRequest, opts ...http.CallOption) (*TaskReply, error) {
	var out TaskReply
	pattern := "/api/v1/tasks/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSchedulerGetTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetTaskExecutions 获取任务执行历史
func (c *SchedulerHTTPClientImpl) GetTaskExecutions(ctx context.Context, in *GetTaskExecutionsRequest, opts ...http.CallOption) (*ListExecutionsReply, error) {
	var out ListExecutionsReply
	pattern := "/api/v1/tasks/{task_id}/executions"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSchedulerGetTaskExecutions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListTasks 任务列表查询
func (c *SchedulerHTTPClientImpl) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...http.CallOption) (*ListTasksReply, error) {
	var out ListTasksReply
	pattern := "/api/v1/tasks"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSchedulerListTasks))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PauseTask 暂停任务
func (c *SchedulerHTTPClientImpl) PauseTask(ctx context.Context, in *PauseTaskRequest, opts ...http.CallOption) (*TaskReply, error) {
	var out TaskReply
	pattern := "/api/v1/tasks/{id}/pause"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSchedulerPauseTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ResumeTask 恢复任务
func (c *SchedulerHTTPClientImpl) ResumeTask(ctx context.Context, in *ResumeTaskRequest, opts ...http.CallOption) (*TaskReply, error) {
	var out TaskReply
	pattern := "/api/v1/tasks/{id}/resume"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSchedulerResumeTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateTask 更新任务
func (c *SchedulerHTTPClientImpl) UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...http.CallOption) (*TaskReply, error) {
	var out TaskReply
	pattern := "/api/v1/tasks/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSchedulerUpdateTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
