// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.2
// source: scheduler/v1/scheduler.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 任务类型枚举
type TaskType int32

const (
	TaskType_TASK_TYPE_UNSPECIFIED TaskType = 0
	TaskType_IMMEDIATE             TaskType = 1 // 立即执行
	TaskType_SCHEDULED             TaskType = 2 // 指定时间执行
	TaskType_CRON                  TaskType = 3 // Cron 表达式执行
	TaskType_INTERVAL              TaskType = 4 // 固定间隔执行
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "TASK_TYPE_UNSPECIFIED",
		1: "IMMEDIATE",
		2: "SCHEDULED",
		3: "CRON",
		4: "INTERVAL",
	}
	TaskType_value = map[string]int32{
		"TASK_TYPE_UNSPECIFIED": 0,
		"IMMEDIATE":             1,
		"SCHEDULED":             2,
		"CRON":                  3,
		"INTERVAL":              4,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_scheduler_v1_scheduler_proto_enumTypes[0].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_scheduler_v1_scheduler_proto_enumTypes[0]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{0}
}

// 任务状态枚举
type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_PENDING                 TaskStatus = 1 // 等待中
	TaskStatus_RUNNING                 TaskStatus = 2 // 运行中
	TaskStatus_PAUSED                  TaskStatus = 3 // 已暂停
	TaskStatus_COMPLETED               TaskStatus = 4 // 已完成
	TaskStatus_FAILED                  TaskStatus = 5 // 失败
	TaskStatus_CANCELLED               TaskStatus = 6 // 已取消
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "PENDING",
		2: "RUNNING",
		3: "PAUSED",
		4: "COMPLETED",
		5: "FAILED",
		6: "CANCELLED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"PENDING":                 1,
		"RUNNING":                 2,
		"PAUSED":                  3,
		"COMPLETED":               4,
		"FAILED":                  5,
		"CANCELLED":               6,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_scheduler_v1_scheduler_proto_enumTypes[1].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_scheduler_v1_scheduler_proto_enumTypes[1]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{1}
}

// 执行状态枚举
type ExecutionStatus int32

const (
	ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED ExecutionStatus = 0
	ExecutionStatus_QUEUED                       ExecutionStatus = 1 // 队列中
	ExecutionStatus_EXECUTING                    ExecutionStatus = 2 // 执行中
	ExecutionStatus_SUCCESS                      ExecutionStatus = 3 // 成功
	ExecutionStatus_EXECUTION_FAILED             ExecutionStatus = 4 // 失败
	ExecutionStatus_TIMEOUT                      ExecutionStatus = 5 // 超时
	ExecutionStatus_EXECUTION_CANCELLED          ExecutionStatus = 6 // 已取消
)

// Enum value maps for ExecutionStatus.
var (
	ExecutionStatus_name = map[int32]string{
		0: "EXECUTION_STATUS_UNSPECIFIED",
		1: "QUEUED",
		2: "EXECUTING",
		3: "SUCCESS",
		4: "EXECUTION_FAILED",
		5: "TIMEOUT",
		6: "EXECUTION_CANCELLED",
	}
	ExecutionStatus_value = map[string]int32{
		"EXECUTION_STATUS_UNSPECIFIED": 0,
		"QUEUED":                       1,
		"EXECUTING":                    2,
		"SUCCESS":                      3,
		"EXECUTION_FAILED":             4,
		"TIMEOUT":                      5,
		"EXECUTION_CANCELLED":          6,
	}
)

func (x ExecutionStatus) Enum() *ExecutionStatus {
	p := new(ExecutionStatus)
	*p = x
	return p
}

func (x ExecutionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_scheduler_v1_scheduler_proto_enumTypes[2].Descriptor()
}

func (ExecutionStatus) Type() protoreflect.EnumType {
	return &file_scheduler_v1_scheduler_proto_enumTypes[2]
}

func (x ExecutionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionStatus.Descriptor instead.
func (ExecutionStatus) EnumDescriptor() ([]byte, []int) {
	return file_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{2}
}

// 创建任务请求
type CreateTaskRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                             // 任务名称
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`               // 任务描述
	Type        TaskType               `protobuf:"varint,3,opt,name=type,proto3,enum=scheduler.v1.TaskType" json:"type,omitempty"` // 任务类型
	Schedule    string                 `protobuf:"bytes,4,opt,name=schedule,proto3" json:"schedule,omitempty"`                     // 调度配置：
	// - IMMEDIATE: 可为空
	// - SCHEDULED: RFC3339格式时间戳，如 "2024-12-31T15:04:05Z"
	// - CRON: Cron表达式，如 "0 */5 * * * *"
	// - INTERVAL: 间隔秒数，如 "300" 表示每5分钟
	Handler       string            `protobuf:"bytes,5,opt,name=handler,proto3" json:"handler,omitempty"`                                                                             // 处理器名称
	Payload       string            `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`                                                                             // 任务负载（JSON格式）
	Timeout       int32             `protobuf:"varint,7,opt,name=timeout,proto3" json:"timeout,omitempty"`                                                                            // 超时时间（秒）
	Metadata      map[string]string `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 元数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTaskRequest) GetType() TaskType {
	if x != nil {
		return x.Type
	}
	return TaskType_TASK_TYPE_UNSPECIFIED
}

func (x *CreateTaskRequest) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *CreateTaskRequest) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

func (x *CreateTaskRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *CreateTaskRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *CreateTaskRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 获取任务请求
type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *GetTaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 更新任务请求
type UpdateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Schedule      string                 `protobuf:"bytes,4,opt,name=schedule,proto3" json:"schedule,omitempty"`
	Payload       string                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Timeout       int32                  `protobuf:"varint,6,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateTaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateTaskRequest) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *UpdateTaskRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *UpdateTaskRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *UpdateTaskRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 删除任务请求
type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteTaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 任务列表请求
type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                                  // 页码
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`          // 每页数量
	Status        TaskStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=scheduler.v1.TaskStatus" json:"status,omitempty"` // 状态筛选
	Type          TaskType               `protobuf:"varint,4,opt,name=type,proto3,enum=scheduler.v1.TaskType" json:"type,omitempty"`       // 类型筛选
	Keyword       string                 `protobuf:"bytes,5,opt,name=keyword,proto3" json:"keyword,omitempty"`                             // 关键词搜索
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{4}
}

func (x *ListTasksRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTasksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTasksRequest) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *ListTasksRequest) GetType() TaskType {
	if x != nil {
		return x.Type
	}
	return TaskType_TASK_TYPE_UNSPECIFIED
}

func (x *ListTasksRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

// 执行任务请求
type ExecuteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // 可选的负载覆盖
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTaskRequest) Reset() {
	*x = ExecuteTaskRequest{}
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTaskRequest) ProtoMessage() {}

func (x *ExecuteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTaskRequest.ProtoReflect.Descriptor instead.
func (*ExecuteTaskRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteTaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ExecuteTaskRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

// 暂停任务请求
type PauseTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseTaskRequest) Reset() {
	*x = PauseTaskRequest{}
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseTaskRequest) ProtoMessage() {}

func (x *PauseTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseTaskRequest.ProtoReflect.Descriptor instead.
func (*PauseTaskRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{6}
}

func (x *PauseTaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 恢复任务请求
type ResumeTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeTaskRequest) Reset() {
	*x = ResumeTaskRequest{}
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeTaskRequest) ProtoMessage() {}

func (x *ResumeTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeTaskRequest.ProtoReflect.Descriptor instead.
func (*ResumeTaskRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{7}
}

func (x *ResumeTaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 获取任务执行历史请求
type GetTaskExecutionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Status        ExecutionStatus        `protobuf:"varint,4,opt,name=status,proto3,enum=scheduler.v1.ExecutionStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskExecutionsRequest) Reset() {
	*x = GetTaskExecutionsRequest{}
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskExecutionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskExecutionsRequest) ProtoMessage() {}

func (x *GetTaskExecutionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskExecutionsRequest.ProtoReflect.Descriptor instead.
func (*GetTaskExecutionsRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{8}
}

func (x *GetTaskExecutionsRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *GetTaskExecutionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetTaskExecutionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetTaskExecutionsRequest) GetStatus() ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED
}

// 获取执行详情请求
type GetExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionRequest) Reset() {
	*x = GetExecutionRequest{}
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionRequest) ProtoMessage() {}

func (x *GetExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionRequest.ProtoReflect.Descriptor instead.
func (*GetExecutionRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{9}
}

func (x *GetExecutionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 取消执行请求
type CancelExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelExecutionRequest) Reset() {
	*x = CancelExecutionRequest{}
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelExecutionRequest) ProtoMessage() {}

func (x *CancelExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelExecutionRequest.ProtoReflect.Descriptor instead.
func (*CancelExecutionRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{10}
}

func (x *CancelExecutionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 任务响应
type TaskReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type           TaskType               `protobuf:"varint,4,opt,name=type,proto3,enum=scheduler.v1.TaskType" json:"type,omitempty"`
	Status         TaskStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=scheduler.v1.TaskStatus" json:"status,omitempty"`
	Schedule       string                 `protobuf:"bytes,6,opt,name=schedule,proto3" json:"schedule,omitempty"`
	Handler        string                 `protobuf:"bytes,7,opt,name=handler,proto3" json:"handler,omitempty"`
	Payload        string                 `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"`
	Timeout        int32                  `protobuf:"varint,9,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	NextRunTime    *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=next_run_time,json=nextRunTime,proto3" json:"next_run_time,omitempty"`         // 下次执行时间
	ExecutionCount int64                  `protobuf:"varint,14,opt,name=execution_count,json=executionCount,proto3" json:"execution_count,omitempty"` // 执行次数
	SuccessCount   int64                  `protobuf:"varint,15,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`       // 成功次数
	FailedCount    int64                  `protobuf:"varint,16,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`          // 失败次数
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskReply) Reset() {
	*x = TaskReply{}
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskReply) ProtoMessage() {}

func (x *TaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskReply.ProtoReflect.Descriptor instead.
func (*TaskReply) Descriptor() ([]byte, []int) {
	return file_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{11}
}

func (x *TaskReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TaskReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskReply) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TaskReply) GetType() TaskType {
	if x != nil {
		return x.Type
	}
	return TaskType_TASK_TYPE_UNSPECIFIED
}

func (x *TaskReply) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *TaskReply) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *TaskReply) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

func (x *TaskReply) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *TaskReply) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *TaskReply) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TaskReply) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TaskReply) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *TaskReply) GetNextRunTime() *timestamppb.Timestamp {
	if x != nil {
		return x.NextRunTime
	}
	return nil
}

func (x *TaskReply) GetExecutionCount() int64 {
	if x != nil {
		return x.ExecutionCount
	}
	return 0
}

func (x *TaskReply) GetSuccessCount() int64 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *TaskReply) GetFailedCount() int64 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

// 任务列表响应
type ListTasksReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*TaskReply           `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksReply) Reset() {
	*x = ListTasksReply{}
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksReply) ProtoMessage() {}

func (x *ListTasksReply) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksReply.ProtoReflect.Descriptor instead.
func (*ListTasksReply) Descriptor() ([]byte, []int) {
	return file_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{12}
}

func (x *ListTasksReply) GetTasks() []*TaskReply {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListTasksReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListTasksReply) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTasksReply) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 任务执行响应
type TaskExecutionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   int64                  `protobuf:"varint,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskExecutionReply) Reset() {
	*x = TaskExecutionReply{}
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskExecutionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExecutionReply) ProtoMessage() {}

func (x *TaskExecutionReply) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskExecutionReply.ProtoReflect.Descriptor instead.
func (*TaskExecutionReply) Descriptor() ([]byte, []int) {
	return file_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{13}
}

func (x *TaskExecutionReply) GetExecutionId() int64 {
	if x != nil {
		return x.ExecutionId
	}
	return 0
}

func (x *TaskExecutionReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 执行记录响应
type ExecutionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskId        int64                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskName      string                 `protobuf:"bytes,3,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	Status        ExecutionStatus        `protobuf:"varint,4,opt,name=status,proto3,enum=scheduler.v1.ExecutionStatus" json:"status,omitempty"`
	NodeId        string                 `protobuf:"bytes,5,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // 执行节点ID
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Duration      int32                  `protobuf:"varint,8,opt,name=duration,proto3" json:"duration,omitempty"`                        // 执行耗时（毫秒）
	Result        string                 `protobuf:"bytes,9,opt,name=result,proto3" json:"result,omitempty"`                             // 执行结果
	Error         string                 `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`                              // 错误信息
	RetryCount    int32                  `protobuf:"varint,11,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"` // 重试次数
	Payload       string                 `protobuf:"bytes,12,opt,name=payload,proto3" json:"payload,omitempty"`                          // 执行负载
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionReply) Reset() {
	*x = ExecutionReply{}
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionReply) ProtoMessage() {}

func (x *ExecutionReply) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionReply.ProtoReflect.Descriptor instead.
func (*ExecutionReply) Descriptor() ([]byte, []int) {
	return file_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{14}
}

func (x *ExecutionReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ExecutionReply) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ExecutionReply) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *ExecutionReply) GetStatus() ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED
}

func (x *ExecutionReply) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ExecutionReply) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ExecutionReply) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *ExecutionReply) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *ExecutionReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ExecutionReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecutionReply) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *ExecutionReply) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

// 执行历史列表响应
type ListExecutionsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Executions    []*ExecutionReply      `protobuf:"bytes,1,rep,name=executions,proto3" json:"executions,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExecutionsReply) Reset() {
	*x = ListExecutionsReply{}
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExecutionsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExecutionsReply) ProtoMessage() {}

func (x *ListExecutionsReply) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExecutionsReply.ProtoReflect.Descriptor instead.
func (*ListExecutionsReply) Descriptor() ([]byte, []int) {
	return file_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{15}
}

func (x *ListExecutionsReply) GetExecutions() []*ExecutionReply {
	if x != nil {
		return x.Executions
	}
	return nil
}

func (x *ListExecutionsReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListExecutionsReply) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListExecutionsReply) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_scheduler_v1_scheduler_proto protoreflect.FileDescriptor

const file_scheduler_v1_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x1cscheduler/v1/scheduler.proto\x12\fscheduler.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xe7\x02\n" +
	"\x11CreateTaskRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12*\n" +
	"\x04type\x18\x03 \x01(\x0e2\x16.scheduler.v1.TaskTypeR\x04type\x12\x1a\n" +
	"\bschedule\x18\x04 \x01(\tR\bschedule\x12\x18\n" +
	"\ahandler\x18\x05 \x01(\tR\ahandler\x12\x18\n" +
	"\apayload\x18\x06 \x01(\tR\apayload\x12\x18\n" +
	"\atimeout\x18\a \x01(\x05R\atimeout\x12I\n" +
	"\bmetadata\x18\b \x03(\v2-.scheduler.v1.CreateTaskRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\" \n" +
	"\x0eGetTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xb1\x02\n" +
	"\x11UpdateTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bschedule\x18\x04 \x01(\tR\bschedule\x12\x18\n" +
	"\apayload\x18\x05 \x01(\tR\apayload\x12\x18\n" +
	"\atimeout\x18\x06 \x01(\x05R\atimeout\x12I\n" +
	"\bmetadata\x18\a \x03(\v2-.scheduler.v1.UpdateTaskRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"#\n" +
	"\x11DeleteTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xbb\x01\n" +
	"\x10ListTasksRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x120\n" +
	"\x06status\x18\x03 \x01(\x0e2\x18.scheduler.v1.TaskStatusR\x06status\x12*\n" +
	"\x04type\x18\x04 \x01(\x0e2\x16.scheduler.v1.TaskTypeR\x04type\x12\x18\n" +
	"\akeyword\x18\x05 \x01(\tR\akeyword\">\n" +
	"\x12ExecuteTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\"\"\n" +
	"\x10PauseTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"#\n" +
	"\x11ResumeTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x9b\x01\n" +
	"\x18GetTaskExecutionsRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x125\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1d.scheduler.v1.ExecutionStatusR\x06status\"%\n" +
	"\x13GetExecutionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"(\n" +
	"\x16CancelExecutionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xc0\x05\n" +
	"\tTaskReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12*\n" +
	"\x04type\x18\x04 \x01(\x0e2\x16.scheduler.v1.TaskTypeR\x04type\x120\n" +
	"\x06status\x18\x05 \x01(\x0e2\x18.scheduler.v1.TaskStatusR\x06status\x12\x1a\n" +
	"\bschedule\x18\x06 \x01(\tR\bschedule\x12\x18\n" +
	"\ahandler\x18\a \x01(\tR\ahandler\x12\x18\n" +
	"\apayload\x18\b \x01(\tR\apayload\x12\x18\n" +
	"\atimeout\x18\t \x01(\x05R\atimeout\x12A\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2%.scheduler.v1.TaskReply.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12>\n" +
	"\rnext_run_time\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\vnextRunTime\x12'\n" +
	"\x0fexecution_count\x18\x0e \x01(\x03R\x0eexecutionCount\x12#\n" +
	"\rsuccess_count\x18\x0f \x01(\x03R\fsuccessCount\x12!\n" +
	"\ffailed_count\x18\x10 \x01(\x03R\vfailedCount\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x86\x01\n" +
	"\x0eListTasksReply\x12-\n" +
	"\x05tasks\x18\x01 \x03(\v2\x17.scheduler.v1.TaskReplyR\x05tasks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"Q\n" +
	"\x12TaskExecutionReply\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\x03R\vexecutionId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9d\x03\n" +
	"\x0eExecutionReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x03R\x06taskId\x12\x1b\n" +
	"\ttask_name\x18\x03 \x01(\tR\btaskName\x125\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1d.scheduler.v1.ExecutionStatusR\x06status\x12\x17\n" +
	"\anode_id\x18\x05 \x01(\tR\x06nodeId\x129\n" +
	"\n" +
	"start_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1a\n" +
	"\bduration\x18\b \x01(\x05R\bduration\x12\x16\n" +
	"\x06result\x18\t \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\x12\x1f\n" +
	"\vretry_count\x18\v \x01(\x05R\n" +
	"retryCount\x12\x18\n" +
	"\apayload\x18\f \x01(\tR\apayload\"\x9a\x01\n" +
	"\x13ListExecutionsReply\x12<\n" +
	"\n" +
	"executions\x18\x01 \x03(\v2\x1c.scheduler.v1.ExecutionReplyR\n" +
	"executions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize*[\n" +
	"\bTaskType\x12\x19\n" +
	"\x15TASK_TYPE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tIMMEDIATE\x10\x01\x12\r\n" +
	"\tSCHEDULED\x10\x02\x12\b\n" +
	"\x04CRON\x10\x03\x12\f\n" +
	"\bINTERVAL\x10\x04*y\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\v\n" +
	"\aRUNNING\x10\x02\x12\n" +
	"\n" +
	"\x06PAUSED\x10\x03\x12\r\n" +
	"\tCOMPLETED\x10\x04\x12\n" +
	"\n" +
	"\x06FAILED\x10\x05\x12\r\n" +
	"\tCANCELLED\x10\x06*\x97\x01\n" +
	"\x0fExecutionStatus\x12 \n" +
	"\x1cEXECUTION_STATUS_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06QUEUED\x10\x01\x12\r\n" +
	"\tEXECUTING\x10\x02\x12\v\n" +
	"\aSUCCESS\x10\x03\x12\x14\n" +
	"\x10EXECUTION_FAILED\x10\x04\x12\v\n" +
	"\aTIMEOUT\x10\x05\x12\x17\n" +
	"\x13EXECUTION_CANCELLED\x10\x062\xcc\t\n" +
	"\tScheduler\x12`\n" +
	"\n" +
	"CreateTask\x12\x1f.scheduler.v1.CreateTaskRequest\x1a\x17.scheduler.v1.TaskReply\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/tasks\x12\\\n" +
	"\aGetTask\x12\x1c.scheduler.v1.GetTaskRequest\x1a\x17.scheduler.v1.TaskReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/tasks/{id}\x12e\n" +
	"\n" +
	"UpdateTask\x12\x1f.scheduler.v1.UpdateTaskRequest\x1a\x17.scheduler.v1.TaskReply\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/api/v1/tasks/{id}\x12a\n" +
	"\n" +
	"DeleteTask\x12\x1f.scheduler.v1.DeleteTaskRequest\x1a\x16.google.protobuf.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/api/v1/tasks/{id}\x12`\n" +
	"\tListTasks\x12\x1e.scheduler.v1.ListTasksRequest\x1a\x1c.scheduler.v1.ListTasksReply\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/tasks\x12x\n" +
	"\vExecuteTask\x12 .scheduler.v1.ExecuteTaskRequest\x1a .scheduler.v1.TaskExecutionReply\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/tasks/{id}/execute\x12i\n" +
	"\tPauseTask\x12\x1e.scheduler.v1.PauseTaskRequest\x1a\x17.scheduler.v1.TaskReply\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v1/tasks/{id}/pause\x12l\n" +
	"\n" +
	"ResumeTask\x12\x1f.scheduler.v1.ResumeTaskRequest\x1a\x17.scheduler.v1.TaskReply\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/v1/tasks/{id}/resume\x12\x8a\x01\n" +
	"\x11GetTaskExecutions\x12&.scheduler.v1.GetTaskExecutionsRequest\x1a!.scheduler.v1.ListExecutionsReply\"*\x82\xd3\xe4\x93\x02$\x12\"/api/v1/tasks/{task_id}/executions\x12p\n" +
	"\fGetExecution\x12!.scheduler.v1.GetExecutionRequest\x1a\x1c.scheduler.v1.ExecutionReply\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/executions/{id}\x12\x80\x01\n" +
	"\x0fCancelExecution\x12$.scheduler.v1.CancelExecutionRequest\x1a\x1c.scheduler.v1.ExecutionReply\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/api/v1/executions/{id}/cancelBW\n" +
	"\x1bdev.kratos.api.scheduler.v1B\x10SchedulerProtoV1P\x01Z$heytom-scheduler/api/scheduler/v1;v1b\x06proto3"

var (
	file_scheduler_v1_scheduler_proto_rawDescOnce sync.Once
	file_scheduler_v1_scheduler_proto_rawDescData []byte
)

func file_scheduler_v1_scheduler_proto_rawDescGZIP() []byte {
	file_scheduler_v1_scheduler_proto_rawDescOnce.Do(func() {
		file_scheduler_v1_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scheduler_v1_scheduler_proto_rawDesc), len(file_scheduler_v1_scheduler_proto_rawDesc)))
	})
	return file_scheduler_v1_scheduler_proto_rawDescData
}

var file_scheduler_v1_scheduler_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_scheduler_v1_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_scheduler_v1_scheduler_proto_goTypes = []any{
	(TaskType)(0),                    // 0: scheduler.v1.TaskType
	(TaskStatus)(0),                  // 1: scheduler.v1.TaskStatus
	(ExecutionStatus)(0),             // 2: scheduler.v1.ExecutionStatus
	(*CreateTaskRequest)(nil),        // 3: scheduler.v1.CreateTaskRequest
	(*GetTaskRequest)(nil),           // 4: scheduler.v1.GetTaskRequest
	(*UpdateTaskRequest)(nil),        // 5: scheduler.v1.UpdateTaskRequest
	(*DeleteTaskRequest)(nil),        // 6: scheduler.v1.DeleteTaskRequest
	(*ListTasksRequest)(nil),         // 7: scheduler.v1.ListTasksRequest
	(*ExecuteTaskRequest)(nil),       // 8: scheduler.v1.ExecuteTaskRequest
	(*PauseTaskRequest)(nil),         // 9: scheduler.v1.PauseTaskRequest
	(*ResumeTaskRequest)(nil),        // 10: scheduler.v1.ResumeTaskRequest
	(*GetTaskExecutionsRequest)(nil), // 11: scheduler.v1.GetTaskExecutionsRequest
	(*GetExecutionRequest)(nil),      // 12: scheduler.v1.GetExecutionRequest
	(*CancelExecutionRequest)(nil),   // 13: scheduler.v1.CancelExecutionRequest
	(*TaskReply)(nil),                // 14: scheduler.v1.TaskReply
	(*ListTasksReply)(nil),           // 15: scheduler.v1.ListTasksReply
	(*TaskExecutionReply)(nil),       // 16: scheduler.v1.TaskExecutionReply
	(*ExecutionReply)(nil),           // 17: scheduler.v1.ExecutionReply
	(*ListExecutionsReply)(nil),      // 18: scheduler.v1.ListExecutionsReply
	nil,                              // 19: scheduler.v1.CreateTaskRequest.MetadataEntry
	nil,                              // 20: scheduler.v1.UpdateTaskRequest.MetadataEntry
	nil,                              // 21: scheduler.v1.TaskReply.MetadataEntry
	(*timestamppb.Timestamp)(nil),    // 22: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 23: google.protobuf.Empty
}
var file_scheduler_v1_scheduler_proto_depIdxs = []int32{
	0,  // 0: scheduler.v1.CreateTaskRequest.type:type_name -> scheduler.v1.TaskType
	19, // 1: scheduler.v1.CreateTaskRequest.metadata:type_name -> scheduler.v1.CreateTaskRequest.MetadataEntry
	20, // 2: scheduler.v1.UpdateTaskRequest.metadata:type_name -> scheduler.v1.UpdateTaskRequest.MetadataEntry
	1,  // 3: scheduler.v1.ListTasksRequest.status:type_name -> scheduler.v1.TaskStatus
	0,  // 4: scheduler.v1.ListTasksRequest.type:type_name -> scheduler.v1.TaskType
	2,  // 5: scheduler.v1.GetTaskExecutionsRequest.status:type_name -> scheduler.v1.ExecutionStatus
	0,  // 6: scheduler.v1.TaskReply.type:type_name -> scheduler.v1.TaskType
	1,  // 7: scheduler.v1.TaskReply.status:type_name -> scheduler.v1.TaskStatus
	21, // 8: scheduler.v1.TaskReply.metadata:type_name -> scheduler.v1.TaskReply.MetadataEntry
	22, // 9: scheduler.v1.TaskReply.created_at:type_name -> google.protobuf.Timestamp
	22, // 10: scheduler.v1.TaskReply.updated_at:type_name -> google.protobuf.Timestamp
	22, // 11: scheduler.v1.TaskReply.next_run_time:type_name -> google.protobuf.Timestamp
	14, // 12: scheduler.v1.ListTasksReply.tasks:type_name -> scheduler.v1.TaskReply
	2,  // 13: scheduler.v1.ExecutionReply.status:type_name -> scheduler.v1.ExecutionStatus
	22, // 14: scheduler.v1.ExecutionReply.start_time:type_name -> google.protobuf.Timestamp
	22, // 15: scheduler.v1.ExecutionReply.end_time:type_name -> google.protobuf.Timestamp
	17, // 16: scheduler.v1.ListExecutionsReply.executions:type_name -> scheduler.v1.ExecutionReply
	3,  // 17: scheduler.v1.Scheduler.CreateTask:input_type -> scheduler.v1.CreateTaskRequest
	4,  // 18: scheduler.v1.Scheduler.GetTask:input_type -> scheduler.v1.GetTaskRequest
	5,  // 19: scheduler.v1.Scheduler.UpdateTask:input_type -> scheduler.v1.UpdateTaskRequest
	6,  // 20: scheduler.v1.Scheduler.DeleteTask:input_type -> scheduler.v1.DeleteTaskRequest
	7,  // 21: scheduler.v1.Scheduler.ListTasks:input_type -> scheduler.v1.ListTasksRequest
	8,  // 22: scheduler.v1.Scheduler.ExecuteTask:input_type -> scheduler.v1.ExecuteTaskRequest
	9,  // 23: scheduler.v1.Scheduler.PauseTask:input_type -> scheduler.v1.PauseTaskRequest
	10, // 24: scheduler.v1.Scheduler.ResumeTask:input_type -> scheduler.v1.ResumeTaskRequest
	11, // 25: scheduler.v1.Scheduler.GetTaskExecutions:input_type -> scheduler.v1.GetTaskExecutionsRequest
	12, // 26: scheduler.v1.Scheduler.GetExecution:input_type -> scheduler.v1.GetExecutionRequest
	13, // 27: scheduler.v1.Scheduler.CancelExecution:input_type -> scheduler.v1.CancelExecutionRequest
	14, // 28: scheduler.v1.Scheduler.CreateTask:output_type -> scheduler.v1.TaskReply
	14, // 29: scheduler.v1.Scheduler.GetTask:output_type -> scheduler.v1.TaskReply
	14, // 30: scheduler.v1.Scheduler.UpdateTask:output_type -> scheduler.v1.TaskReply
	23, // 31: scheduler.v1.Scheduler.DeleteTask:output_type -> google.protobuf.Empty
	15, // 32: scheduler.v1.Scheduler.ListTasks:output_type -> scheduler.v1.ListTasksReply
	16, // 33: scheduler.v1.Scheduler.ExecuteTask:output_type -> scheduler.v1.TaskExecutionReply
	14, // 34: scheduler.v1.Scheduler.PauseTask:output_type -> scheduler.v1.TaskReply
	14, // 35: scheduler.v1.Scheduler.ResumeTask:output_type -> scheduler.v1.TaskReply
	18, // 36: scheduler.v1.Scheduler.GetTaskExecutions:output_type -> scheduler.v1.ListExecutionsReply
	17, // 37: scheduler.v1.Scheduler.GetExecution:output_type -> scheduler.v1.ExecutionReply
	17, // 38: scheduler.v1.Scheduler.CancelExecution:output_type -> scheduler.v1.ExecutionReply
	28, // [28:39] is the sub-list for method output_type
	17, // [17:28] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_scheduler_v1_scheduler_proto_init() }
func file_scheduler_v1_scheduler_proto_init() {
	if File_scheduler_v1_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scheduler_v1_scheduler_proto_rawDesc), len(file_scheduler_v1_scheduler_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scheduler_v1_scheduler_proto_goTypes,
		DependencyIndexes: file_scheduler_v1_scheduler_proto_depIdxs,
		EnumInfos:         file_scheduler_v1_scheduler_proto_enumTypes,
		MessageInfos:      file_scheduler_v1_scheduler_proto_msgTypes,
	}.Build()
	File_scheduler_v1_scheduler_proto = out.File
	file_scheduler_v1_scheduler_proto_goTypes = nil
	file_scheduler_v1_scheduler_proto_depIdxs = nil
}
