// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"heytom-scheduler/internal/biz"
	"heytom-scheduler/internal/conf"
	"heytom-scheduler/internal/data"
	"heytom-scheduler/internal/server"
	"heytom-scheduler/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	taskRepo := data.NewTaskRepo(dataData, logger)
	taskUsecase := biz.NewTaskUsecase(taskRepo, logger)
	executionRepo := data.NewExecutionRepo(dataData, logger)
	executionUsecase := biz.NewExecutionUsecase(executionRepo, logger)
	schedulerService := service.NewSchedulerService(taskUsecase, executionUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, schedulerService, logger)
	httpServer := server.NewHTTPServer(confServer, schedulerService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
