// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.2
// source: api/task_scheduler.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExecutionMode defines how a task should be executed
type ExecutionMode int32

const (
	ExecutionMode_EXECUTION_MODE_UNSPECIFIED ExecutionMode = 0
	ExecutionMode_EXECUTION_MODE_IMMEDIATE   ExecutionMode = 1 // 立即执行
	ExecutionMode_EXECUTION_MODE_SCHEDULED   ExecutionMode = 2 // 定时执行
	ExecutionMode_EXECUTION_MODE_INTERVAL    ExecutionMode = 3 // 固定间隔
	ExecutionMode_EXECUTION_MODE_CRON        ExecutionMode = 4 // Cron表达式
)

// Enum value maps for ExecutionMode.
var (
	ExecutionMode_name = map[int32]string{
		0: "EXECUTION_MODE_UNSPECIFIED",
		1: "EXECUTION_MODE_IMMEDIATE",
		2: "EXECUTION_MODE_SCHEDULED",
		3: "EXECUTION_MODE_INTERVAL",
		4: "EXECUTION_MODE_CRON",
	}
	ExecutionMode_value = map[string]int32{
		"EXECUTION_MODE_UNSPECIFIED": 0,
		"EXECUTION_MODE_IMMEDIATE":   1,
		"EXECUTION_MODE_SCHEDULED":   2,
		"EXECUTION_MODE_INTERVAL":    3,
		"EXECUTION_MODE_CRON":        4,
	}
)

func (x ExecutionMode) Enum() *ExecutionMode {
	p := new(ExecutionMode)
	*p = x
	return p
}

func (x ExecutionMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionMode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_task_scheduler_proto_enumTypes[0].Descriptor()
}

func (ExecutionMode) Type() protoreflect.EnumType {
	return &file_api_task_scheduler_proto_enumTypes[0]
}

func (x ExecutionMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionMode.Descriptor instead.
func (ExecutionMode) EnumDescriptor() ([]byte, []int) {
	return file_api_task_scheduler_proto_rawDescGZIP(), []int{0}
}

// TaskStatus represents the current state of a task
type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_STATUS_PENDING     TaskStatus = 1 // 等待中
	TaskStatus_TASK_STATUS_RUNNING     TaskStatus = 2 // 执行中
	TaskStatus_TASK_STATUS_SUCCESS     TaskStatus = 3 // 成功
	TaskStatus_TASK_STATUS_FAILED      TaskStatus = 4 // 失败
	TaskStatus_TASK_STATUS_CANCELLED   TaskStatus = 5 // 已取消
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_PENDING",
		2: "TASK_STATUS_RUNNING",
		3: "TASK_STATUS_SUCCESS",
		4: "TASK_STATUS_FAILED",
		5: "TASK_STATUS_CANCELLED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"TASK_STATUS_PENDING":     1,
		"TASK_STATUS_RUNNING":     2,
		"TASK_STATUS_SUCCESS":     3,
		"TASK_STATUS_FAILED":      4,
		"TASK_STATUS_CANCELLED":   5,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_task_scheduler_proto_enumTypes[1].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_api_task_scheduler_proto_enumTypes[1]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_task_scheduler_proto_rawDescGZIP(), []int{1}
}

// CallbackProtocol defines the callback protocol type
type CallbackProtocol int32

const (
	CallbackProtocol_CALLBACK_PROTOCOL_UNSPECIFIED CallbackProtocol = 0
	CallbackProtocol_CALLBACK_PROTOCOL_HTTP        CallbackProtocol = 1 // HTTP协议
	CallbackProtocol_CALLBACK_PROTOCOL_GRPC        CallbackProtocol = 2 // gRPC协议
)

// Enum value maps for CallbackProtocol.
var (
	CallbackProtocol_name = map[int32]string{
		0: "CALLBACK_PROTOCOL_UNSPECIFIED",
		1: "CALLBACK_PROTOCOL_HTTP",
		2: "CALLBACK_PROTOCOL_GRPC",
	}
	CallbackProtocol_value = map[string]int32{
		"CALLBACK_PROTOCOL_UNSPECIFIED": 0,
		"CALLBACK_PROTOCOL_HTTP":        1,
		"CALLBACK_PROTOCOL_GRPC":        2,
	}
)

func (x CallbackProtocol) Enum() *CallbackProtocol {
	p := new(CallbackProtocol)
	*p = x
	return p
}

func (x CallbackProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallbackProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_api_task_scheduler_proto_enumTypes[2].Descriptor()
}

func (CallbackProtocol) Type() protoreflect.EnumType {
	return &file_api_task_scheduler_proto_enumTypes[2]
}

func (x CallbackProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallbackProtocol.Descriptor instead.
func (CallbackProtocol) EnumDescriptor() ([]byte, []int) {
	return file_api_task_scheduler_proto_rawDescGZIP(), []int{2}
}

// ServiceDiscoveryType defines the service discovery mechanism
type ServiceDiscoveryType int32

const (
	ServiceDiscoveryType_SERVICE_DISCOVERY_TYPE_UNSPECIFIED ServiceDiscoveryType = 0
	ServiceDiscoveryType_SERVICE_DISCOVERY_TYPE_STATIC      ServiceDiscoveryType = 1 // 静态地址
	ServiceDiscoveryType_SERVICE_DISCOVERY_TYPE_CONSUL      ServiceDiscoveryType = 2 // Consul
	ServiceDiscoveryType_SERVICE_DISCOVERY_TYPE_ETCD        ServiceDiscoveryType = 3 // Etcd
	ServiceDiscoveryType_SERVICE_DISCOVERY_TYPE_KUBERNETES  ServiceDiscoveryType = 4 // Kubernetes
)

// Enum value maps for ServiceDiscoveryType.
var (
	ServiceDiscoveryType_name = map[int32]string{
		0: "SERVICE_DISCOVERY_TYPE_UNSPECIFIED",
		1: "SERVICE_DISCOVERY_TYPE_STATIC",
		2: "SERVICE_DISCOVERY_TYPE_CONSUL",
		3: "SERVICE_DISCOVERY_TYPE_ETCD",
		4: "SERVICE_DISCOVERY_TYPE_KUBERNETES",
	}
	ServiceDiscoveryType_value = map[string]int32{
		"SERVICE_DISCOVERY_TYPE_UNSPECIFIED": 0,
		"SERVICE_DISCOVERY_TYPE_STATIC":      1,
		"SERVICE_DISCOVERY_TYPE_CONSUL":      2,
		"SERVICE_DISCOVERY_TYPE_ETCD":        3,
		"SERVICE_DISCOVERY_TYPE_KUBERNETES":  4,
	}
)

func (x ServiceDiscoveryType) Enum() *ServiceDiscoveryType {
	p := new(ServiceDiscoveryType)
	*p = x
	return p
}

func (x ServiceDiscoveryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceDiscoveryType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_task_scheduler_proto_enumTypes[3].Descriptor()
}

func (ServiceDiscoveryType) Type() protoreflect.EnumType {
	return &file_api_task_scheduler_proto_enumTypes[3]
}

func (x ServiceDiscoveryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceDiscoveryType.Descriptor instead.
func (ServiceDiscoveryType) EnumDescriptor() ([]byte, []int) {
	return file_api_task_scheduler_proto_rawDescGZIP(), []int{3}
}

// ChannelType defines notification channel types
type ChannelType int32

const (
	ChannelType_CHANNEL_TYPE_UNSPECIFIED ChannelType = 0
	ChannelType_CHANNEL_TYPE_EMAIL       ChannelType = 1 // 邮件
	ChannelType_CHANNEL_TYPE_WEBHOOK     ChannelType = 2 // Webhook
	ChannelType_CHANNEL_TYPE_SMS         ChannelType = 3 // 短信
)

// Enum value maps for ChannelType.
var (
	ChannelType_name = map[int32]string{
		0: "CHANNEL_TYPE_UNSPECIFIED",
		1: "CHANNEL_TYPE_EMAIL",
		2: "CHANNEL_TYPE_WEBHOOK",
		3: "CHANNEL_TYPE_SMS",
	}
	ChannelType_value = map[string]int32{
		"CHANNEL_TYPE_UNSPECIFIED": 0,
		"CHANNEL_TYPE_EMAIL":       1,
		"CHANNEL_TYPE_WEBHOOK":     2,
		"CHANNEL_TYPE_SMS":         3,
	}
)

func (x ChannelType) Enum() *ChannelType {
	p := new(ChannelType)
	*p = x
	return p
}

func (x ChannelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChannelType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_task_scheduler_proto_enumTypes[4].Descriptor()
}

func (ChannelType) Type() protoreflect.EnumType {
	return &file_api_task_scheduler_proto_enumTypes[4]
}

func (x ChannelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChannelType.Descriptor instead.
func (ChannelType) EnumDescriptor() ([]byte, []int) {
	return file_api_task_scheduler_proto_rawDescGZIP(), []int{4}
}

// ScheduleConfig contains scheduling parameters
type ScheduleConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ScheduledTime   int64                  `protobuf:"varint,1,opt,name=scheduled_time,json=scheduledTime,proto3" json:"scheduled_time,omitempty"`       // 定时执行时间（Unix时间戳，秒）
	IntervalSeconds int64                  `protobuf:"varint,2,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"` // 间隔时长（秒）
	CronExpr        string                 `protobuf:"bytes,3,opt,name=cron_expr,json=cronExpr,proto3" json:"cron_expr,omitempty"`                       // Cron表达式
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ScheduleConfig) Reset() {
	*x = ScheduleConfig{}
	mi := &file_api_task_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleConfig) ProtoMessage() {}

func (x *ScheduleConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleConfig.ProtoReflect.Descriptor instead.
func (*ScheduleConfig) Descriptor() ([]byte, []int) {
	return file_api_task_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *ScheduleConfig) GetScheduledTime() int64 {
	if x != nil {
		return x.ScheduledTime
	}
	return 0
}

func (x *ScheduleConfig) GetIntervalSeconds() int64 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *ScheduleConfig) GetCronExpr() string {
	if x != nil {
		return x.CronExpr
	}
	return ""
}

// CallbackConfig contains callback parameters
type CallbackConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Protocol       CallbackProtocol       `protobuf:"varint,1,opt,name=protocol,proto3,enum=taskscheduler.CallbackProtocol" json:"protocol,omitempty"`                                     // 回调协议类型
	Url            string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`                                                                                    // 回调URL（HTTP）或地址（gRPC）
	Method         string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`                                                                              // HTTP方法（仅HTTP使用）
	GrpcService    string                 `protobuf:"bytes,4,opt,name=grpc_service,json=grpcService,proto3" json:"grpc_service,omitempty"`                                                 // gRPC服务名（仅gRPC使用）
	GrpcMethod     string                 `protobuf:"bytes,5,opt,name=grpc_method,json=grpcMethod,proto3" json:"grpc_method,omitempty"`                                                    // gRPC方法名（仅gRPC使用）
	Headers        map[string]string      `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`  // 请求头（HTTP）或元数据（gRPC）
	TimeoutSeconds int64                  `protobuf:"varint,7,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`                                       // 超时时间（秒）
	IsAsync        bool                   `protobuf:"varint,8,opt,name=is_async,json=isAsync,proto3" json:"is_async,omitempty"`                                                            // 是否异步
	ServiceName    string                 `protobuf:"bytes,9,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`                                                 // 服务名（用于服务发现）
	DiscoveryType  ServiceDiscoveryType   `protobuf:"varint,10,opt,name=discovery_type,json=discoveryType,proto3,enum=taskscheduler.ServiceDiscoveryType" json:"discovery_type,omitempty"` // 服务发现类型
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CallbackConfig) Reset() {
	*x = CallbackConfig{}
	mi := &file_api_task_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackConfig) ProtoMessage() {}

func (x *CallbackConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackConfig.ProtoReflect.Descriptor instead.
func (*CallbackConfig) Descriptor() ([]byte, []int) {
	return file_api_task_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *CallbackConfig) GetProtocol() CallbackProtocol {
	if x != nil {
		return x.Protocol
	}
	return CallbackProtocol_CALLBACK_PROTOCOL_UNSPECIFIED
}

func (x *CallbackConfig) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CallbackConfig) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CallbackConfig) GetGrpcService() string {
	if x != nil {
		return x.GrpcService
	}
	return ""
}

func (x *CallbackConfig) GetGrpcMethod() string {
	if x != nil {
		return x.GrpcMethod
	}
	return ""
}

func (x *CallbackConfig) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *CallbackConfig) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *CallbackConfig) GetIsAsync() bool {
	if x != nil {
		return x.IsAsync
	}
	return false
}

func (x *CallbackConfig) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *CallbackConfig) GetDiscoveryType() ServiceDiscoveryType {
	if x != nil {
		return x.DiscoveryType
	}
	return ServiceDiscoveryType_SERVICE_DISCOVERY_TYPE_UNSPECIFIED
}

// RetryPolicy defines retry behavior for failed tasks
type RetryPolicy struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	MaxRetries           int32                  `protobuf:"varint,1,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`                                 // 最大重试次数（0表示不重试）
	RetryIntervalSeconds int64                  `protobuf:"varint,2,opt,name=retry_interval_seconds,json=retryIntervalSeconds,proto3" json:"retry_interval_seconds,omitempty"` // 重试间隔（秒）
	BackoffFactor        float64                `protobuf:"fixed64,3,opt,name=backoff_factor,json=backoffFactor,proto3" json:"backoff_factor,omitempty"`                       // 退避因子（指数退避）
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RetryPolicy) Reset() {
	*x = RetryPolicy{}
	mi := &file_api_task_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryPolicy) ProtoMessage() {}

func (x *RetryPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryPolicy.ProtoReflect.Descriptor instead.
func (*RetryPolicy) Descriptor() ([]byte, []int) {
	return file_api_task_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *RetryPolicy) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *RetryPolicy) GetRetryIntervalSeconds() int64 {
	if x != nil {
		return x.RetryIntervalSeconds
	}
	return 0
}

func (x *RetryPolicy) GetBackoffFactor() float64 {
	if x != nil {
		return x.BackoffFactor
	}
	return 0
}

// NotificationChannel represents a notification delivery method
type NotificationChannel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ChannelType            `protobuf:"varint,1,opt,name=type,proto3,enum=taskscheduler.ChannelType" json:"type,omitempty"`                                               // 渠道类型
	Config        map[string]string      `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 渠道配置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationChannel) Reset() {
	*x = NotificationChannel{}
	mi := &file_api_task_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationChannel) ProtoMessage() {}

func (x *NotificationChannel) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationChannel.ProtoReflect.Descriptor instead.
func (*NotificationChannel) Descriptor() ([]byte, []int) {
	return file_api_task_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *NotificationChannel) GetType() ChannelType {
	if x != nil {
		return x.Type
	}
	return ChannelType_CHANNEL_TYPE_UNSPECIFIED
}

func (x *NotificationChannel) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

// AlertPolicy defines alerting rules
type AlertPolicy struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	EnableFailureAlert      bool                   `protobuf:"varint,1,opt,name=enable_failure_alert,json=enableFailureAlert,proto3" json:"enable_failure_alert,omitempty"`                // 启用失败报警
	RetryThreshold          int32                  `protobuf:"varint,2,opt,name=retry_threshold,json=retryThreshold,proto3" json:"retry_threshold,omitempty"`                              // 重试次数阈值
	TimeoutThresholdSeconds int64                  `protobuf:"varint,3,opt,name=timeout_threshold_seconds,json=timeoutThresholdSeconds,proto3" json:"timeout_threshold_seconds,omitempty"` // 超时阈值（秒）
	Channels                []*NotificationChannel `protobuf:"bytes,4,rep,name=channels,proto3" json:"channels,omitempty"`                                                                 // 通知渠道
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AlertPolicy) Reset() {
	*x = AlertPolicy{}
	mi := &file_api_task_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertPolicy) ProtoMessage() {}

func (x *AlertPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertPolicy.ProtoReflect.Descriptor instead.
func (*AlertPolicy) Descriptor() ([]byte, []int) {
	return file_api_task_scheduler_proto_rawDescGZIP(), []int{4}
}

func (x *AlertPolicy) GetEnableFailureAlert() bool {
	if x != nil {
		return x.EnableFailureAlert
	}
	return false
}

func (x *AlertPolicy) GetRetryThreshold() int32 {
	if x != nil {
		return x.RetryThreshold
	}
	return 0
}

func (x *AlertPolicy) GetTimeoutThresholdSeconds() int64 {
	if x != nil {
		return x.TimeoutThresholdSeconds
	}
	return 0
}

func (x *AlertPolicy) GetChannels() []*NotificationChannel {
	if x != nil {
		return x.Channels
	}
	return nil
}

// Task represents a schedulable work unit
type Task struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                        // 任务唯一标识
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                                                    // 任务名称
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                                                                      // 任务描述
	ParentId         string                 `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`                                                            // 父任务ID（子任务时非空）
	ExecutionMode    ExecutionMode          `protobuf:"varint,5,opt,name=execution_mode,json=executionMode,proto3,enum=taskscheduler.ExecutionMode" json:"execution_mode,omitempty"`           // 执行模式
	ScheduleConfig   *ScheduleConfig        `protobuf:"bytes,6,opt,name=schedule_config,json=scheduleConfig,proto3" json:"schedule_config,omitempty"`                                          // 调度配置
	CallbackConfig   *CallbackConfig        `protobuf:"bytes,7,opt,name=callback_config,json=callbackConfig,proto3" json:"callback_config,omitempty"`                                          // 回调配置
	RetryPolicy      *RetryPolicy           `protobuf:"bytes,8,opt,name=retry_policy,json=retryPolicy,proto3" json:"retry_policy,omitempty"`                                                   // 重试策略
	ConcurrencyLimit int32                  `protobuf:"varint,9,opt,name=concurrency_limit,json=concurrencyLimit,proto3" json:"concurrency_limit,omitempty"`                                   // 子任务并发限制
	AlertPolicy      *AlertPolicy           `protobuf:"bytes,10,opt,name=alert_policy,json=alertPolicy,proto3" json:"alert_policy,omitempty"`                                                  // 报警策略
	Status           TaskStatus             `protobuf:"varint,11,opt,name=status,proto3,enum=taskscheduler.TaskStatus" json:"status,omitempty"`                                                // 任务状态
	RetryCount       int32                  `protobuf:"varint,12,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`                                                    // 已重试次数
	NodeId           string                 `protobuf:"bytes,13,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                                                                 // 执行节点ID
	CreatedAt        int64                  `protobuf:"varint,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                                                       // 创建时间（Unix时间戳，秒）
	UpdatedAt        int64                  `protobuf:"varint,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                                                       // 更新时间（Unix时间戳，秒）
	StartedAt        int64                  `protobuf:"varint,16,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`                                                       // 开始执行时间（Unix时间戳，秒）
	CompletedAt      int64                  `protobuf:"varint,17,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`                                                 // 完成时间（Unix时间戳，秒）
	Metadata         map[string]string      `protobuf:"bytes,18,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 元数据
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_api_task_scheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_scheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_api_task_scheduler_proto_rawDescGZIP(), []int{5}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Task) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Task) GetExecutionMode() ExecutionMode {
	if x != nil {
		return x.ExecutionMode
	}
	return ExecutionMode_EXECUTION_MODE_UNSPECIFIED
}

func (x *Task) GetScheduleConfig() *ScheduleConfig {
	if x != nil {
		return x.ScheduleConfig
	}
	return nil
}

func (x *Task) GetCallbackConfig() *CallbackConfig {
	if x != nil {
		return x.CallbackConfig
	}
	return nil
}

func (x *Task) GetRetryPolicy() *RetryPolicy {
	if x != nil {
		return x.RetryPolicy
	}
	return nil
}

func (x *Task) GetConcurrencyLimit() int32 {
	if x != nil {
		return x.ConcurrencyLimit
	}
	return 0
}

func (x *Task) GetAlertPolicy() *AlertPolicy {
	if x != nil {
		return x.AlertPolicy
	}
	return nil
}

func (x *Task) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *Task) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *Task) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Task) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Task) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Task) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *Task) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

func (x *Task) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// CreateTaskRequest contains parameters for creating a task
type CreateTaskRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                                                    // 任务名称
	Description      string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`                                                                      // 任务描述
	ParentId         string                 `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`                                                            // 父任务ID（子任务时非空）
	ExecutionMode    ExecutionMode          `protobuf:"varint,4,opt,name=execution_mode,json=executionMode,proto3,enum=taskscheduler.ExecutionMode" json:"execution_mode,omitempty"`           // 执行模式
	ScheduleConfig   *ScheduleConfig        `protobuf:"bytes,5,opt,name=schedule_config,json=scheduleConfig,proto3" json:"schedule_config,omitempty"`                                          // 调度配置
	CallbackConfig   *CallbackConfig        `protobuf:"bytes,6,opt,name=callback_config,json=callbackConfig,proto3" json:"callback_config,omitempty"`                                          // 回调配置
	RetryPolicy      *RetryPolicy           `protobuf:"bytes,7,opt,name=retry_policy,json=retryPolicy,proto3" json:"retry_policy,omitempty"`                                                   // 重试策略
	ConcurrencyLimit int32                  `protobuf:"varint,8,opt,name=concurrency_limit,json=concurrencyLimit,proto3" json:"concurrency_limit,omitempty"`                                   // 子任务并发限制
	AlertPolicy      *AlertPolicy           `protobuf:"bytes,9,opt,name=alert_policy,json=alertPolicy,proto3" json:"alert_policy,omitempty"`                                                   // 报警策略
	Metadata         map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 元数据
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_api_task_scheduler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_scheduler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_task_scheduler_proto_rawDescGZIP(), []int{6}
}

func (x *CreateTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTaskRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *CreateTaskRequest) GetExecutionMode() ExecutionMode {
	if x != nil {
		return x.ExecutionMode
	}
	return ExecutionMode_EXECUTION_MODE_UNSPECIFIED
}

func (x *CreateTaskRequest) GetScheduleConfig() *ScheduleConfig {
	if x != nil {
		return x.ScheduleConfig
	}
	return nil
}

func (x *CreateTaskRequest) GetCallbackConfig() *CallbackConfig {
	if x != nil {
		return x.CallbackConfig
	}
	return nil
}

func (x *CreateTaskRequest) GetRetryPolicy() *RetryPolicy {
	if x != nil {
		return x.RetryPolicy
	}
	return nil
}

func (x *CreateTaskRequest) GetConcurrencyLimit() int32 {
	if x != nil {
		return x.ConcurrencyLimit
	}
	return 0
}

func (x *CreateTaskRequest) GetAlertPolicy() *AlertPolicy {
	if x != nil {
		return x.AlertPolicy
	}
	return nil
}

func (x *CreateTaskRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// CreateTaskResponse contains the created task
type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"` // 创建的任务
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_api_task_scheduler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_scheduler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_task_scheduler_proto_rawDescGZIP(), []int{7}
}

func (x *CreateTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// GetTaskRequest contains parameters for retrieving a task
type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // 任务ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_api_task_scheduler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_scheduler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_task_scheduler_proto_rawDescGZIP(), []int{8}
}

func (x *GetTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// GetTaskResponse contains the retrieved task
type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"` // 任务信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_api_task_scheduler_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_scheduler_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_task_scheduler_proto_rawDescGZIP(), []int{9}
}

func (x *GetTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// ListTasksRequest contains parameters for listing tasks
type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        TaskStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=taskscheduler.TaskStatus" json:"status,omitempty"` // 按状态筛选
	ParentId      string                 `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`            // 按父任务ID筛选
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                  // 按节点ID筛选
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`                                 // 限制返回数量
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`                               // 偏移量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_api_task_scheduler_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_scheduler_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_api_task_scheduler_proto_rawDescGZIP(), []int{10}
}

func (x *ListTasksRequest) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *ListTasksRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *ListTasksRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ListTasksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTasksRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// ListTasksResponse contains the list of tasks
type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`  // 任务列表
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"` // 任务数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_api_task_scheduler_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_scheduler_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_api_task_scheduler_proto_rawDescGZIP(), []int{11}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListTasksResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// CancelTaskRequest contains parameters for cancelling a task
type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // 任务ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_api_task_scheduler_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_scheduler_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_task_scheduler_proto_rawDescGZIP(), []int{12}
}

func (x *CancelTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// CancelTaskResponse contains the result of cancelling a task
type CancelTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`             // 响应消息
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // 任务ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_api_task_scheduler_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_scheduler_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_task_scheduler_proto_rawDescGZIP(), []int{13}
}

func (x *CancelTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CancelTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// GetTaskStatusRequest contains parameters for retrieving task status
type GetTaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // 任务ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskStatusRequest) Reset() {
	*x = GetTaskStatusRequest{}
	mi := &file_api_task_scheduler_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskStatusRequest) ProtoMessage() {}

func (x *GetTaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_scheduler_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskStatusRequest.ProtoReflect.Descriptor instead.
func (*GetTaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_task_scheduler_proto_rawDescGZIP(), []int{14}
}

func (x *GetTaskStatusRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// GetTaskStatusResponse contains the task status information
type GetTaskStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                  // 任务ID
	Status        TaskStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=taskscheduler.TaskStatus" json:"status,omitempty"` // 任务状态
	RetryCount    int32                  `protobuf:"varint,3,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`     // 已重试次数
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`        // 创建时间（Unix时间戳，秒）
	UpdatedAt     int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`        // 更新时间（Unix时间戳，秒）
	StartedAt     int64                  `protobuf:"varint,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`        // 开始执行时间（Unix时间戳，秒）
	CompletedAt   int64                  `protobuf:"varint,7,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`  // 完成时间（Unix时间戳，秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskStatusResponse) Reset() {
	*x = GetTaskStatusResponse{}
	mi := &file_api_task_scheduler_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskStatusResponse) ProtoMessage() {}

func (x *GetTaskStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_scheduler_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskStatusResponse.ProtoReflect.Descriptor instead.
func (*GetTaskStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_task_scheduler_proto_rawDescGZIP(), []int{15}
}

func (x *GetTaskStatusResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetTaskStatusResponse) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *GetTaskStatusResponse) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *GetTaskStatusResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GetTaskStatusResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *GetTaskStatusResponse) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *GetTaskStatusResponse) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

var File_api_task_scheduler_proto protoreflect.FileDescriptor

const file_api_task_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x18api/task_scheduler.proto\x12\rtaskscheduler\"\x7f\n" +
	"\x0eScheduleConfig\x12%\n" +
	"\x0escheduled_time\x18\x01 \x01(\x03R\rscheduledTime\x12)\n" +
	"\x10interval_seconds\x18\x02 \x01(\x03R\x0fintervalSeconds\x12\x1b\n" +
	"\tcron_expr\x18\x03 \x01(\tR\bcronExpr\"\xf0\x03\n" +
	"\x0eCallbackConfig\x12;\n" +
	"\bprotocol\x18\x01 \x01(\x0e2\x1f.taskscheduler.CallbackProtocolR\bprotocol\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12!\n" +
	"\fgrpc_service\x18\x04 \x01(\tR\vgrpcService\x12\x1f\n" +
	"\vgrpc_method\x18\x05 \x01(\tR\n" +
	"grpcMethod\x12D\n" +
	"\aheaders\x18\x06 \x03(\v2*.taskscheduler.CallbackConfig.HeadersEntryR\aheaders\x12'\n" +
	"\x0ftimeout_seconds\x18\a \x01(\x03R\x0etimeoutSeconds\x12\x19\n" +
	"\bis_async\x18\b \x01(\bR\aisAsync\x12!\n" +
	"\fservice_name\x18\t \x01(\tR\vserviceName\x12J\n" +
	"\x0ediscovery_type\x18\n" +
	" \x01(\x0e2#.taskscheduler.ServiceDiscoveryTypeR\rdiscoveryType\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8b\x01\n" +
	"\vRetryPolicy\x12\x1f\n" +
	"\vmax_retries\x18\x01 \x01(\x05R\n" +
	"maxRetries\x124\n" +
	"\x16retry_interval_seconds\x18\x02 \x01(\x03R\x14retryIntervalSeconds\x12%\n" +
	"\x0ebackoff_factor\x18\x03 \x01(\x01R\rbackoffFactor\"\xc8\x01\n" +
	"\x13NotificationChannel\x12.\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.taskscheduler.ChannelTypeR\x04type\x12F\n" +
	"\x06config\x18\x02 \x03(\v2..taskscheduler.NotificationChannel.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe4\x01\n" +
	"\vAlertPolicy\x120\n" +
	"\x14enable_failure_alert\x18\x01 \x01(\bR\x12enableFailureAlert\x12'\n" +
	"\x0fretry_threshold\x18\x02 \x01(\x05R\x0eretryThreshold\x12:\n" +
	"\x19timeout_threshold_seconds\x18\x03 \x01(\x03R\x17timeoutThresholdSeconds\x12>\n" +
	"\bchannels\x18\x04 \x03(\v2\".taskscheduler.NotificationChannelR\bchannels\"\xd2\x06\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\tR\bparentId\x12C\n" +
	"\x0eexecution_mode\x18\x05 \x01(\x0e2\x1c.taskscheduler.ExecutionModeR\rexecutionMode\x12F\n" +
	"\x0fschedule_config\x18\x06 \x01(\v2\x1d.taskscheduler.ScheduleConfigR\x0escheduleConfig\x12F\n" +
	"\x0fcallback_config\x18\a \x01(\v2\x1d.taskscheduler.CallbackConfigR\x0ecallbackConfig\x12=\n" +
	"\fretry_policy\x18\b \x01(\v2\x1a.taskscheduler.RetryPolicyR\vretryPolicy\x12+\n" +
	"\x11concurrency_limit\x18\t \x01(\x05R\x10concurrencyLimit\x12=\n" +
	"\falert_policy\x18\n" +
	" \x01(\v2\x1a.taskscheduler.AlertPolicyR\valertPolicy\x121\n" +
	"\x06status\x18\v \x01(\x0e2\x19.taskscheduler.TaskStatusR\x06status\x12\x1f\n" +
	"\vretry_count\x18\f \x01(\x05R\n" +
	"retryCount\x12\x17\n" +
	"\anode_id\x18\r \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"started_at\x18\x10 \x01(\x03R\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\x11 \x01(\x03R\vcompletedAt\x12=\n" +
	"\bmetadata\x18\x12 \x03(\v2!.taskscheduler.Task.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xef\x04\n" +
	"\x11CreateTaskRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\tR\bparentId\x12C\n" +
	"\x0eexecution_mode\x18\x04 \x01(\x0e2\x1c.taskscheduler.ExecutionModeR\rexecutionMode\x12F\n" +
	"\x0fschedule_config\x18\x05 \x01(\v2\x1d.taskscheduler.ScheduleConfigR\x0escheduleConfig\x12F\n" +
	"\x0fcallback_config\x18\x06 \x01(\v2\x1d.taskscheduler.CallbackConfigR\x0ecallbackConfig\x12=\n" +
	"\fretry_policy\x18\a \x01(\v2\x1a.taskscheduler.RetryPolicyR\vretryPolicy\x12+\n" +
	"\x11concurrency_limit\x18\b \x01(\x05R\x10concurrencyLimit\x12=\n" +
	"\falert_policy\x18\t \x01(\v2\x1a.taskscheduler.AlertPolicyR\valertPolicy\x12J\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2..taskscheduler.CreateTaskRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"=\n" +
	"\x12CreateTaskResponse\x12'\n" +
	"\x04task\x18\x01 \x01(\v2\x13.taskscheduler.TaskR\x04task\")\n" +
	"\x0eGetTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\":\n" +
	"\x0fGetTaskResponse\x12'\n" +
	"\x04task\x18\x01 \x01(\v2\x13.taskscheduler.TaskR\x04task\"\xa9\x01\n" +
	"\x10ListTasksRequest\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.taskscheduler.TaskStatusR\x06status\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\tR\bparentId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\"T\n" +
	"\x11ListTasksResponse\x12)\n" +
	"\x05tasks\x18\x01 \x03(\v2\x13.taskscheduler.TaskR\x05tasks\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\",\n" +
	"\x11CancelTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"G\n" +
	"\x12CancelTaskResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\"/\n" +
	"\x14GetTaskStatusRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\x84\x02\n" +
	"\x15GetTaskStatusResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.taskscheduler.TaskStatusR\x06status\x12\x1f\n" +
	"\vretry_count\x18\x03 \x01(\x05R\n" +
	"retryCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"started_at\x18\x06 \x01(\x03R\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\a \x01(\x03R\vcompletedAt*\xa1\x01\n" +
	"\rExecutionMode\x12\x1e\n" +
	"\x1aEXECUTION_MODE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18EXECUTION_MODE_IMMEDIATE\x10\x01\x12\x1c\n" +
	"\x18EXECUTION_MODE_SCHEDULED\x10\x02\x12\x1b\n" +
	"\x17EXECUTION_MODE_INTERVAL\x10\x03\x12\x17\n" +
	"\x13EXECUTION_MODE_CRON\x10\x04*\xa7\x01\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TASK_STATUS_PENDING\x10\x01\x12\x17\n" +
	"\x13TASK_STATUS_RUNNING\x10\x02\x12\x17\n" +
	"\x13TASK_STATUS_SUCCESS\x10\x03\x12\x16\n" +
	"\x12TASK_STATUS_FAILED\x10\x04\x12\x19\n" +
	"\x15TASK_STATUS_CANCELLED\x10\x05*m\n" +
	"\x10CallbackProtocol\x12!\n" +
	"\x1dCALLBACK_PROTOCOL_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16CALLBACK_PROTOCOL_HTTP\x10\x01\x12\x1a\n" +
	"\x16CALLBACK_PROTOCOL_GRPC\x10\x02*\xcc\x01\n" +
	"\x14ServiceDiscoveryType\x12&\n" +
	"\"SERVICE_DISCOVERY_TYPE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dSERVICE_DISCOVERY_TYPE_STATIC\x10\x01\x12!\n" +
	"\x1dSERVICE_DISCOVERY_TYPE_CONSUL\x10\x02\x12\x1f\n" +
	"\x1bSERVICE_DISCOVERY_TYPE_ETCD\x10\x03\x12%\n" +
	"!SERVICE_DISCOVERY_TYPE_KUBERNETES\x10\x04*s\n" +
	"\vChannelType\x12\x1c\n" +
	"\x18CHANNEL_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CHANNEL_TYPE_EMAIL\x10\x01\x12\x18\n" +
	"\x14CHANNEL_TYPE_WEBHOOK\x10\x02\x12\x14\n" +
	"\x10CHANNEL_TYPE_SMS\x10\x032\xb2\x03\n" +
	"\x14TaskSchedulerService\x12Q\n" +
	"\n" +
	"CreateTask\x12 .taskscheduler.CreateTaskRequest\x1a!.taskscheduler.CreateTaskResponse\x12H\n" +
	"\aGetTask\x12\x1d.taskscheduler.GetTaskRequest\x1a\x1e.taskscheduler.GetTaskResponse\x12N\n" +
	"\tListTasks\x12\x1f.taskscheduler.ListTasksRequest\x1a .taskscheduler.ListTasksResponse\x12Q\n" +
	"\n" +
	"CancelTask\x12 .taskscheduler.CancelTaskRequest\x1a!.taskscheduler.CancelTaskResponse\x12Z\n" +
	"\rGetTaskStatus\x12#.taskscheduler.GetTaskStatusRequest\x1a$.taskscheduler.GetTaskStatusResponseB\x17Z\x15task-scheduler/api/pbb\x06proto3"

var (
	file_api_task_scheduler_proto_rawDescOnce sync.Once
	file_api_task_scheduler_proto_rawDescData []byte
)

func file_api_task_scheduler_proto_rawDescGZIP() []byte {
	file_api_task_scheduler_proto_rawDescOnce.Do(func() {
		file_api_task_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_task_scheduler_proto_rawDesc), len(file_api_task_scheduler_proto_rawDesc)))
	})
	return file_api_task_scheduler_proto_rawDescData
}

var file_api_task_scheduler_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_api_task_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_api_task_scheduler_proto_goTypes = []any{
	(ExecutionMode)(0),            // 0: taskscheduler.ExecutionMode
	(TaskStatus)(0),               // 1: taskscheduler.TaskStatus
	(CallbackProtocol)(0),         // 2: taskscheduler.CallbackProtocol
	(ServiceDiscoveryType)(0),     // 3: taskscheduler.ServiceDiscoveryType
	(ChannelType)(0),              // 4: taskscheduler.ChannelType
	(*ScheduleConfig)(nil),        // 5: taskscheduler.ScheduleConfig
	(*CallbackConfig)(nil),        // 6: taskscheduler.CallbackConfig
	(*RetryPolicy)(nil),           // 7: taskscheduler.RetryPolicy
	(*NotificationChannel)(nil),   // 8: taskscheduler.NotificationChannel
	(*AlertPolicy)(nil),           // 9: taskscheduler.AlertPolicy
	(*Task)(nil),                  // 10: taskscheduler.Task
	(*CreateTaskRequest)(nil),     // 11: taskscheduler.CreateTaskRequest
	(*CreateTaskResponse)(nil),    // 12: taskscheduler.CreateTaskResponse
	(*GetTaskRequest)(nil),        // 13: taskscheduler.GetTaskRequest
	(*GetTaskResponse)(nil),       // 14: taskscheduler.GetTaskResponse
	(*ListTasksRequest)(nil),      // 15: taskscheduler.ListTasksRequest
	(*ListTasksResponse)(nil),     // 16: taskscheduler.ListTasksResponse
	(*CancelTaskRequest)(nil),     // 17: taskscheduler.CancelTaskRequest
	(*CancelTaskResponse)(nil),    // 18: taskscheduler.CancelTaskResponse
	(*GetTaskStatusRequest)(nil),  // 19: taskscheduler.GetTaskStatusRequest
	(*GetTaskStatusResponse)(nil), // 20: taskscheduler.GetTaskStatusResponse
	nil,                           // 21: taskscheduler.CallbackConfig.HeadersEntry
	nil,                           // 22: taskscheduler.NotificationChannel.ConfigEntry
	nil,                           // 23: taskscheduler.Task.MetadataEntry
	nil,                           // 24: taskscheduler.CreateTaskRequest.MetadataEntry
}
var file_api_task_scheduler_proto_depIdxs = []int32{
	2,  // 0: taskscheduler.CallbackConfig.protocol:type_name -> taskscheduler.CallbackProtocol
	21, // 1: taskscheduler.CallbackConfig.headers:type_name -> taskscheduler.CallbackConfig.HeadersEntry
	3,  // 2: taskscheduler.CallbackConfig.discovery_type:type_name -> taskscheduler.ServiceDiscoveryType
	4,  // 3: taskscheduler.NotificationChannel.type:type_name -> taskscheduler.ChannelType
	22, // 4: taskscheduler.NotificationChannel.config:type_name -> taskscheduler.NotificationChannel.ConfigEntry
	8,  // 5: taskscheduler.AlertPolicy.channels:type_name -> taskscheduler.NotificationChannel
	0,  // 6: taskscheduler.Task.execution_mode:type_name -> taskscheduler.ExecutionMode
	5,  // 7: taskscheduler.Task.schedule_config:type_name -> taskscheduler.ScheduleConfig
	6,  // 8: taskscheduler.Task.callback_config:type_name -> taskscheduler.CallbackConfig
	7,  // 9: taskscheduler.Task.retry_policy:type_name -> taskscheduler.RetryPolicy
	9,  // 10: taskscheduler.Task.alert_policy:type_name -> taskscheduler.AlertPolicy
	1,  // 11: taskscheduler.Task.status:type_name -> taskscheduler.TaskStatus
	23, // 12: taskscheduler.Task.metadata:type_name -> taskscheduler.Task.MetadataEntry
	0,  // 13: taskscheduler.CreateTaskRequest.execution_mode:type_name -> taskscheduler.ExecutionMode
	5,  // 14: taskscheduler.CreateTaskRequest.schedule_config:type_name -> taskscheduler.ScheduleConfig
	6,  // 15: taskscheduler.CreateTaskRequest.callback_config:type_name -> taskscheduler.CallbackConfig
	7,  // 16: taskscheduler.CreateTaskRequest.retry_policy:type_name -> taskscheduler.RetryPolicy
	9,  // 17: taskscheduler.CreateTaskRequest.alert_policy:type_name -> taskscheduler.AlertPolicy
	24, // 18: taskscheduler.CreateTaskRequest.metadata:type_name -> taskscheduler.CreateTaskRequest.MetadataEntry
	10, // 19: taskscheduler.CreateTaskResponse.task:type_name -> taskscheduler.Task
	10, // 20: taskscheduler.GetTaskResponse.task:type_name -> taskscheduler.Task
	1,  // 21: taskscheduler.ListTasksRequest.status:type_name -> taskscheduler.TaskStatus
	10, // 22: taskscheduler.ListTasksResponse.tasks:type_name -> taskscheduler.Task
	1,  // 23: taskscheduler.GetTaskStatusResponse.status:type_name -> taskscheduler.TaskStatus
	11, // 24: taskscheduler.TaskSchedulerService.CreateTask:input_type -> taskscheduler.CreateTaskRequest
	13, // 25: taskscheduler.TaskSchedulerService.GetTask:input_type -> taskscheduler.GetTaskRequest
	15, // 26: taskscheduler.TaskSchedulerService.ListTasks:input_type -> taskscheduler.ListTasksRequest
	17, // 27: taskscheduler.TaskSchedulerService.CancelTask:input_type -> taskscheduler.CancelTaskRequest
	19, // 28: taskscheduler.TaskSchedulerService.GetTaskStatus:input_type -> taskscheduler.GetTaskStatusRequest
	12, // 29: taskscheduler.TaskSchedulerService.CreateTask:output_type -> taskscheduler.CreateTaskResponse
	14, // 30: taskscheduler.TaskSchedulerService.GetTask:output_type -> taskscheduler.GetTaskResponse
	16, // 31: taskscheduler.TaskSchedulerService.ListTasks:output_type -> taskscheduler.ListTasksResponse
	18, // 32: taskscheduler.TaskSchedulerService.CancelTask:output_type -> taskscheduler.CancelTaskResponse
	20, // 33: taskscheduler.TaskSchedulerService.GetTaskStatus:output_type -> taskscheduler.GetTaskStatusResponse
	29, // [29:34] is the sub-list for method output_type
	24, // [24:29] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_api_task_scheduler_proto_init() }
func file_api_task_scheduler_proto_init() {
	if File_api_task_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_task_scheduler_proto_rawDesc), len(file_api_task_scheduler_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_task_scheduler_proto_goTypes,
		DependencyIndexes: file_api_task_scheduler_proto_depIdxs,
		EnumInfos:         file_api_task_scheduler_proto_enumTypes,
		MessageInfos:      file_api_task_scheduler_proto_msgTypes,
	}.Build()
	File_api_task_scheduler_proto = out.File
	file_api_task_scheduler_proto_goTypes = nil
	file_api_task_scheduler_proto_depIdxs = nil
}
